import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Sidebar } from "@/components/Sidebar";
import { readDb } from "@/lib/db";
import { CardConfigProvider } from "@/lib/CardConfigContext";
import { CoachMeChat } from "@/components/CoachMeChat";
import { StorageSetupModal } from "@/components/StorageSetupModal";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const db = readDb();
  const teamMembers = db.team.map(m => ({ id: m.id, name: m.name, role: m.role }));

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[#fafafa] text-slate-800 min-h-screen flex font-sans text-[13px] leading-relaxed">
        <CardConfigProvider initialConfig={db.config.cardConfig} initialGoalModalConfig={db.config.goalModalConfig}>
          <Sidebar teamMembers={teamMembers} />
          <main className="flex-1 overflow-y-auto h-screen">
            {children}
          </main>
          <StorageSetupModal />
          <CoachMeChat />
        </CardConfigProvider>
      </body>
    </html>
  );
}
