import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Sidebar } from "@/components/Sidebar";
import { readDb } from "@/lib/db";
import { CardConfigProvider } from "@/lib/CardConfigContext";
import { CoachMeChat } from "@/components/CoachMeChat";
import { IndexedDBProvider } from "@/components/IndexedDBProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const db = readDb();
  const teamMembers = db.team.map(m => ({ id: m.id, name: m.name, role: m.role }));

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-screen overflow-hidden antialiased`}
    >
      <body className="bg-[#fafafa] text-slate-800 h-screen overflow-hidden flex font-sans text-[13px] leading-relaxed">
        <CardConfigProvider initialConfig={db.config.cardConfig} initialGoalModalConfig={db.config.goalModalConfig}>
          <IndexedDBProvider>
            <Sidebar teamMembers={teamMembers} />
            <main className="flex-1 overflow-y-auto h-screen min-w-0">
              {children}
            </main>
            <CoachMeChat />
          </IndexedDBProvider>
        </CardConfigProvider>
      </body>
    </html>
  );
}
